### ISSUE TITLE
OSError: [Errno 63] File name too long

### ISSUE THREAD

**Issue by Zhangdaoning** [ktnrg45/pyjerasure#1]
Mac OS 12.4
I try to install pyremoteplay 0.3.1, so i need to install pyjerasure.

bogon:pyjerasure daoning$ pip install pyjerasure
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting pyjerasure
  Using cached https://mirrors.aliyun.com/pypi/packages/d8/eb/0efcf7933711832e4b1576b48b90660d7df44f3f75e839658fc4808781bd/pyjerasure-1.0.0.tar.gz (65 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/lt/by3qkhd96lbd8z0hc40v8qsh0000gn/T/pip-install-6mixs8ri/pyjerasure_250d97671c9b44778c9b68625e3689e9/setup.py", line 149, in <module>
          ext_modules=build_extensions(),
        File "/private/var/folders/lt/by3qkhd96lbd8z0hc40v8qsh0000gn/T/pip-install-6mixs8ri/pyjerasure_250d97671c9b44778c9b68625e3689e9/setup.py", line 74, in build_extensions
          include_dirs = [get_include_path()]
        File "/private/var/folders/lt/by3qkhd96lbd8z0hc40v8qsh0000gn/T/pip-install-6mixs8ri/pyjerasure_250d97671c9b44778c9b68625e3689e9/setup.py", line 37, in get_include_path
          if path.is_dir():
        File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1398, in is_dir
          return S_ISDIR(self.stat().st_mode)
        File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1189, in stat
          return self._accessor.stat(self)
      OSError: [Errno 63] File name too long: '"/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx12.0.0 -Wundef-prefix=TARGET_OS_ -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name null -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-strict-return -fno-rounding-math -munwind-tables -target-sdk-version=12.3 -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -tune-cpu generic -debugger-tuning=lldb -target-linker-version 762 -v -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -internal-externc-isystem /Library/Developer/CommandLineTools/usr/include -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -Wno-reserved-identifier -Wno-gnu-folding-constant -Wno-objc-load-method -fdebug-compilation-dir=/private/var/folders/lt/by3qkhd96lbd8z0hc40v8qsh0000gn/T/pip-install-6mixs8ri/pyjerasure_250d97671c9b44778c9b68625e3689e9 -ferror-limit 19 -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -fcommon -clang-vendor-feature=+messageToSelfInClassMethodIdReturnType -clang-vendor-feature=+disableInferNewAvailabilityFromInit -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -clang-vendor-feature=+enableAggressiveVLAFolding -clang-vendor-feature=+revert09abecef7bbf -clang-vendor-feature=+thisNoAlignAttr -clang-vendor-feature=+thisNoNullAttr -mllvm -disable-aligned-alloc-awareness=1 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o - -x c /dev/null'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ktnrg45** [comment]
macos wheels have been uploaded which should fix the installation error
